# Generated by Django 5.2.1 on 2025-05-30 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singer',
            name='song',
        ),
        migrations.AddField(
            model_name='songs',
            name='singer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='api.singer'),
        ),
    ]
