# Generated by Django 5.2.1 on 2025-05-30 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_singer_song_songs_singer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='artist',
        ),
    ]
