# Generated by Django 5.2.1 on 2025-05-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_songs_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='duration',
        ),
        migrations.AddField(
            model_name='songs',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songs',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
